<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petrinet" nsURI="http://petrinet" nsPrefix="petrinet">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PetriNet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noEmptyName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="noEmptyName" value="name.size() > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//Node"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arc" upperBound="-1" eType="#//Arc"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoings" eType="#//Arc"
        eOpposite="#//Arc/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomings" eType="#//Arc"
        eOpposite="#//Arc/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arc">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ArcCoherent poidPositif"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ArcCoherent" value="&#xA;&#x9;&#x9;&#x9;self --un arc doit être entre 1 place et 1 transition&#xA;&#x9;&#x9;&#x9;-> select(e: Arc | e.oclIsKindOf(Arc))&#xA;&#x9;&#x9;&#x9;-> collect(e:Arc |e.oclAsType(Arc))&#xA;&#x9;&#x9;&#x9;-> forAll(a : Arc | (a.source.oclIsKindOf(Place) and a.target.oclIsKindOf(Transition)) or (a.source.oclIsKindOf(Transition) and a.target.oclIsKindOf(Place)))"/>
      <details key="poidPositif" value="weight>=0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//ArcKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Node"
        eOpposite="#//Node/outgoings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Node"
        eOpposite="#//Node/incomings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueNamesTransition minmax minPositif"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueNamesTransition" value="&#xA;&#x9;&#x9;&#x9;self  --2 transitions ne peuvent pas avoir le même nom&#xA;&#x9;&#x9;&#x9;-> select(e: Node | e.oclIsKindOf(Transition)) &#xA;&#x9;&#x9;&#x9;-> collect(e:Node | e.oclAsType(Transition))&#xA;&#x9;&#x9;&#x9;-> forAll(t1,t2 : Transition | t1 &lt;> t2 or t1.name = t2.name)"/>
      <details key="minmax" value="min_time&lt;=max_time"/>
      <details key="minPositif" value="min_time>=0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_time" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_time" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueNamesPlace nbrJetonPositif"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueNamesPlace" value="&#xA;&#x9;&#x9;&#x9;self  --2 places ne peuvent pas avoir le même nom&#xA;&#x9;&#x9;&#x9;-> select(e: Node | e.oclIsKindOf(Place)) &#xA;&#x9;&#x9;&#x9;-> collect(e:Node | e.oclAsType(Place))&#xA;&#x9;&#x9;&#x9;-> forAll(p1,p2 : Place | p1 &lt;> p2 or p1.name = p2.name)"/>
      <details key="nbrJetonPositif" value="marking>=0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marking" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArcKind">
    <eLiterals name="normal"/>
    <eLiterals name="read_arc" value="1"/>
  </eClassifiers>
</ecore:EPackage>
